In [ ]:
import pandas as pd
import ast

In [ ]:
import pandas as pd
from google.colab import drive
#drive.mount('/content/drive')

In [ ]:
#All data uploaded neatly into data frames to mess around with
spotify_songs = pd.read_csv("/content/drive/MyDrive/CIS5500 Group Project/Coding/Data/spotify_550_cleaned/spotify_songs.csv")
#spotify_songs = pd.read_csv("/content/drive/MyDrive/CIS5500 Group Project/Coding/Data/spotify_550/songs.csv")
artists_info = pd.read_csv("/content/drive/MyDrive/CIS5500 Group Project/Coding/Data/spotify_550_cleaned/artists_info.csv")
df_grammy = pd.read_csv("/content/drive/MyDrive/CIS5500 Group Project/Coding/Data/grammy_cleaned/grammy_cleaned.csv")
df_albums_info = pd.read_csv("/content/drive/MyDrive/CIS5500 Group Project/Coding/Data/spotify_550_cleaned/albums_info.csv")

## Load data

In [ ]:
# read songs data
#songs = pd.read_csv('data/songs.csv')
spotify_songs.head()

,song_id,song_name,lyrics,year
0,0Prct5TDjAnEgIqbxcldY9,!,"He said he came from Jamaica,\nhe owned a coup...",2016
1,2ASl4wirkeYm3OWZxXKYuq,!!,"Fuck the bitch, now she running with my kids\n...",2019
2,5tA3ImW310llKo8EMBj2Ga,!!Noble Stabbings!!,You like to stand on the other side\nPoint and...,2002
3,0fROT4kK5oTm8xO8PX6EJF,!I'll Be Back!,"It's been a while, shit, I missed the rehab, p...",2018
4,1xBFhv5faebv3mmwxx7DnS,!Lost!,I would like to give you all my time\nI would ...,2018

In [ ]:
# read artists data
#artists = pd.read_csv('data/artists.csv')
artists_info.head()

,artist_id,artist_name,followers,popularity,genre
0,6YROFUbu5zRCHi2xkir5pk,Brian Hyland,67223,47,Pop
1,5tFRohaO5yEsuJxmMnlCO9,Barns Courtney,602647,62,Electronic
2,3w1Q754jb31h5CXQCcnLNL,Capcom Sound Team,210392,58,Electronic
3,3oDbviiivRWhXwIE8hxkVV,The Beach Boys,5139194,76,Classical
4,60zvRmhQHRxokEB1taAVpN,Beth Malone,1569,29,Classical

In [ ]:
df_grammy.head()

,id,annual_edition,year,award,artist,winner,type,name
0,1,1,1958,Album Of The Year,Van Cliburn,False,album,"Tchaikovsky: Concerto No. 1, In B-Flat Minor, ..."
1,2,1,1958,Album Of The Year,Frank Sinatra,False,album,Only The Lonely
2,3,1,1958,Album Of The Year,Ella Fitzgerald,False,album,Ella Fitzgerald Sings The Irving Berlin Song Book
3,4,1,1958,Album Of The Year,Frank Sinatra,False,album,Come Fly With Me
4,5,1,1958,Album Of The Year,Henry Mancini,True,album,The Music From Peter Gunn

In [ ]:
df_albums_info.head()

                     album_name               artist_id
0                             !  6Xgp2XMz1fhVYe7i6yNAax
1            !!!Going Places!!!  09L3cUdx0hq6qn5bKuJJ4I
2                !I'll Be Back!  6pdcQa7by8IKuoVXvgknlI
3  !K7 Kollections 02: Classics  1hwAhXzyuEUjug2pyNVSvg
4                        !Lost!  6pdcQa7by8IKuoVXvgknlI

In [ ]:
album_mask = df_grammy["award"].str.contains(r"album", case=False, na=False)

song_mask = (
    df_grammy["award"].str.contains(r"song|single|record", case=False, na=False)
    & ~album_mask
)

artist_mask = (
    df_grammy["award"].str.contains(r"artist", case=False, na=False)
    & ~album_mask
    & ~song_mask
)

In [ ]:
df_albums = df_grammy.loc[album_mask, [
    "name", "year", "award", "artist", "annual_edition", "winner"
]]
df_songs = df_grammy.loc[song_mask, [
    "name", "year", "award", "artist", "annual_edition", "winner"
]]
df_artists = df_grammy.loc[artist_mask, [
    "year", "award", "name", "winner"
]]

df_artists = df_artists.dropna(subset=["name"])

In [ ]:
df_songs = df_songs.rename(columns={
    "name": "song_title",
    "artist": "artist_name"
})

df_albums = df_albums.rename(columns={
    "name": "album_title",
    "artist": "artist_name"
})

df_artists = df_artists.rename(columns={
    "name": "artist_name",
})

In [ ]:
df_albums.to_csv("/content/drive/MyDrive/CIS5500 Group Project/Coding/Data/grammy_cleaned/albums_table.csv", index=False)
df_songs.to_csv("/content/drive/MyDrive/CIS5500 Group Project/Coding/Data/grammy_cleaned/songs_table.csv", index=False)
df_artists.to_csv("/content/drive/MyDrive/CIS5500 Group Project/Coding/Data/grammy_cleaned/artists_table.csv", index=False)

In [ ]:
#join spotify song ID's onto grammy data if
# df_grammy = df_grammy.merge(
#     spotify_songs[["song_name", "song_id"]],
#     left_on="name",
#     right_on="song_name",
#     how="left"
# ).drop(columns="song_name")

# df_grammy.loc[df_grammy["type"] != "song", "song_id"] = None

# df_grammy

In [ ]:
#join spotify artist ID's onto grammy data if possible
# df_grammy = df_grammy.merge(
#     artists_info[["artist_name", "artist_id"]],
#     left_on=["artist"],
#     right_on=["artist_name"],
#     how="left"
# ).drop(columns="artist_name")

# df_grammy

In [ ]:
#make new version into csv
#df_grammy.to_csv("grammy_updated_with_ids.csv", index=False)

In [ ]:
#BILLBOARD LINKING

In [ ]:
df_billboard = pd.read_csv("/content/drive/MyDrive/CIS5500 Group Project/Coding/Data/billboard/billboard_updated.csv")

In [ ]:
df_billboard.head()

,id,date,rank,song,artist,last-week,peak-rank,weeks-on-board
0,1,2021-11-06,1,Easy On Me,Adele,1.0,1,3
1,2,2021-11-06,2,Stay,The Kid LAROI & Justin Bieber,2.0,1,16
2,3,2021-11-06,3,Industry Baby,Lil Nas X & Jack Harlow,3.0,1,14
3,4,2021-11-06,4,Fancy Like,Walker Hayes,4.0,3,19
4,5,2021-11-06,5,Bad Habits,Ed Sheeran,5.0,2,18

In [ ]:
# #join spotify artist ID's onto billboard data if possible
# df_billboard = df_billboard.merge(
#     artists_info[["artist_name", "artist_id"]],
#     left_on=["artist"],
#     right_on=["artist_name"],
#     how="left"
# ).drop(columns="artist_name")

# #Identify rows where the merge failed
# missing = df_billboard[df_billboard["artist_id"].isna()].copy()

# #Split only those rows on &
# missing["artist"] = missing["artist"].str.split(" & ")
# missing = missing.explode("artist")

# #Try matching again
# missing = missing.merge(
#     artists_info[["artist_name", "artist_id"]],
#     left_on="artist",
#     right_on="artist_name",
#     how="left"
# ).drop(columns="artist_name")

# #Combine back with original successful rows
# matched = df_billboard[df_billboard["artist_id"].notna()]
# df_billboard = pd.concat([matched, missing], ignore_index=True)

# # df_billboard.drop(df_billboard["artist_id_x"])
# # df_billboard.drop(df_billboard["artist_id_y"])

# df_billboard

In [ ]:
# #First merge normally
# df_billboard = df_billboard.merge(
#     artists_info[["artist_name", "artist_id"]],
#     left_on="artist",
#     right_on="artist_name",
#     how="left"
# ).drop(columns="artist_name")


# #Separate matched vs unmatched
# matched = df_billboard[df_billboard["artist_id"].notna()]
# missing = df_billboard[df_billboard["artist_id"].isna()].copy()


# #Remove old artist_id before retrying merge
# missing = missing.drop(columns="artist_id")


# #Split possible collaborations
# missing["artist"] = missing["artist"].str.split(
#     r"(?i)\s+(?:&|feat\.?|ft\.?|featuring|x|\+)\s+",
#     regex=True
# )

# missing = missing.explode("artist")

# missing["artist"] = missing["artist"].str.strip()

# missing["artist"] = (
#     missing["artist"]
#     .str.replace(r"(?i)^(feat\.?|ft\.?|featuring)\s+", "", regex=True)
# )


# #Try merging again
# missing = missing.merge(
#     artists_info[["artist_name", "artist_id"]],
#     left_on="artist",
#     right_on="artist_name",
#     how="left"
# ).drop(columns="artist_name")


# #Combine results
# df_billboard = pd.concat([matched, missing], ignore_index=True)

In [ ]:
#Replace all collaboration indicators with commas
df_billboard["artist"] = df_billboard["artist"].str.replace(
    r"(?i)\s*(?:&|feat\.?|ft\.?|featuring|x|\+)\s*",
    ",",
    regex=True
)

#Split into lists
df_billboard["artist"] = df_billboard["artist"].str.split(",")

#Expand into multiple rows
df_billboard = df_billboard.explode("artist")

#Clean whitespace
df_billboard["artist"] = df_billboard["artist"].str.strip()

#Rename artist to be artist_name
df_billboard = df_billboard.rename(columns={
    "artist": "artist_name",
    "date": "WeekEndingDate",
    "peak-rank": "PeakRank",
    "weeks-on-board": "WeeksOnBoard",
    "rank": "CurrentRank",
    "song": "SongName"
})

#merge!
df_billboard = df_billboard.merge(
    artists_info[["artist_name", "artist_id"]],
    left_on="artist_name",
    right_on="artist_name",
    how="left"
).drop(columns="artist_name")

#drop duplicates
df_billboard = df_billboard.drop_duplicates()

#drop any where we can't find the artist
df_billboard = df_billboard.dropna(subset=["artist_id"])

#drop id column
df_billboard = df_billboard.drop(columns=['id', 'last-week'])

In [ ]:
df_billboard

,WeekEndingDate,CurrentRank,SongName,PeakRank,WeeksOnBoard,artist_id
0,2021-11-06,1,Easy On Me,1,3,4dpARuHxo51G3z768sgnrY
1,2021-11-06,2,Stay,1,16,2tIP7SsRs7vjIcLrU85W8J
2,2021-11-06,2,Stay,1,16,1uNFoZAHBGtllmzznpCI3s
5,2021-11-06,3,Industry Baby,1,14,2LIk90788K0zvyj2JJVwkJ
6,2021-11-06,4,Fancy Like,3,19,7sKxqpSqbIzphAKAhrqvlf
...,...,...,...,...,...,...
423078,1958-08-04,93,Are You Really Mine,93,1,7bKOOOKEkE918wKOQEhYnp
423079,1958-08-04,94,She Was Only Seventeen (He Was One Year More),94,1,0Xi59sEw38vRvwleSAVqoo
423080,1958-08-04,95,Little Mary,95,1,09C0xjtosNAIXP36wTnWxd
423081,1958-08-04,96,Over And Over,96,1,61VpPyyJn2bitby8tbafzT
423083,1958-08-04,97,I Believe In You,97,1,00ejjVUpGffGIuYA51u6UQ

In [ ]:
#df_billboard.to_csv("billboard_updated.csv", index=False)
df_billboard.to_csv("/content/drive/MyDrive/CIS5500 Group Project/Coding/Data/billboard_cleaned/billboard_final_table.csv", index=False)

In [ ]:
#df = df_billboard.dropna(subset=["artist_id"])

In [ ]:
#df.to_csv("/content/drive/MyDrive/CIS5500 Group Project/Coding/Data/billboard_cleaned/billboard_ids_no_na.csv", index=False)